name: mediscan
description: AI medicine scanner for Alexa+ and Fire TV built with Flutter and AWS Lambda
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.13.0
  camera: ^0.10.5
  http: ^1.2.0
  flutter_tts: ^4.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
